### PR TITLE
Changes for v11

### PR DESCRIPTION
**Pull request by yneshch**
This should be all the fixes needed for V11. It works in my private world, tested multiple times over. Though as always, bugs may exist to let me know if there are any issues you want me to look at. Thanks!

### CODE REVIEW

**Comment by Dyrnwyrm** [comment]
> This should be all the fixes needed for V11. It works in my private world, tested multiple times over. Though as always, bugs may exist to let me know if there are any issues you want me to look at. Thanks!

I posted the url that is on your fix but i got this error

image

**Comment by YakFromStateFarm** [comment]
> > This should be all the fixes needed for V11. It works in my private world, tested multiple times over. Though as always, bugs may exist to let me know if there are any issues you want me to look at. Thanks!
> 
> I posted the url that is on your fix but i got this error
> 
> image

Oh I don't have a release on my branch.  That URL should point back to this module as it currently is. My fork/branch is only in this PR right now. Though if you know what youre doing, you can download the branch and manually apply it. Or just make the change yourself in code too. I just made sure it worked today and found no issues(though I didnt do as extensive a test as possible).

**Comment by Dyrnwyrm** [comment]
> > > This should be all the fixes needed for V11. It works in my private world, tested multiple times over. Though as always, bugs may exist to let me know if there are any issues you want me to look at. Thanks!
> > 
> > 
> > I posted the url that is on your fix but i got this error
> > image
> 
> Oh I don't have a release on my branch. That URL should point back to this module as it currently is. My fork/branch is only in this PR right now. Though if you know what youre doing, you can download the branch and manually apply it. Or just make the change yourself in code too. I just made sure it worked today and found no issues(though I didnt do as extensive a test as possible).

oh okay, thanks

**Comment by JenniferPylko** [comment]
this doesn't appear to be fully working with v11, i'm testing the ddb importer-generated green flame blade macro, and it fails because args[0] is undefined (i can see from debugging statements that args is an empty array).
the error in question:
image
the line throwing the error:
image


reading the code i'm just getting confused... it doesn't seem like it should even be working v10, cos args would be [Event] then getEvent() would turn args into [].

**Comment by JenniferPylko** [comment]
never mind. it wasn't working then started working a few seconds later with no change performed by me:
image
that second INVOKE is literally seconds after the first INVOKE, and now i can no longer reproduce this error

**Pull request merged**
